name: Frontend CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: [ "main" ]
  # Triggers the workflow on pull request events targeting the "main" branch
  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This job is named "build-and-test"
  build-and-test:
    # The type of virtual machine to run the job on
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repository's code so the job can access it
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Node.js (version 20)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm' # Adds caching for npm packages to speed up future runs
          cache-dependency-path: linkhub-app/package-lock.json # Points to the lock file

      # 3. Install dependencies
      # 'npm ci' is used for CI/CD as it installs exact versions
      # Set the working directory to /linkhub-app
      - name: Install dependencies
        run: npm ci
        working-directory: ./linkhub-app

      # 4. Run the Linter (to check code style)
      - name: Run Linter
        run: npm run lint
        working-directory: ./linkhub-app

      # 5. Run the Build (to check for TypeScript errors)
      - name: Run Build
        run: npm run build
        working-directory: ./linkhub-app