bug:
  - '(bug|error|fix|issue|problem|exception|fails|crash)'

critical:
  - '(critical|urgent)'

enhancement:
  - '(feature|feat|enhancement|suggestion|addition|implement|improve)'

documentation:
  - '(documentation|docs|readme|guide|tutorial|instructions)'

question:
  - '(question|how to|help|doubt)'

ui:
  - '(ui|design|style|css|layout)'

backend:
  - '(backend|server|api|database|db|prisma|fastify|auth|jwt)'

frontend:
  - '(frontend|client|react|tailwind|vite|page|component|hook|axios)'

testing:
  - '(test|tests|testing|vitest|jest|testing-library|user-event|e2e|unit test)'

refactor:
  - '(refactor|cleanup|chore|technical debt|optimization)'

ci/cd:
  - '(ci|cd|github actions|workflow|workflows|deployment|build)'

config:
  - '(config|configuration|setup|env|tsconfig|vite\.config|tailwind\.config)'

needs-info:
  - '(incomplete|missing info|more details)'

dependencies:
  - '(dependencies|deps|package|npm|dependabot|vulnerability)'

good first issue:
  - '(good first issue)'

help wanted:
  - '(help wanted)'