# .github/labeler.yml (Con límites de palabra \b)

- labels: ["bug"]
  title: '(?i)\b(bug|error|fix|issue|problem|exception|fails|crash)\b'
  body: '(?i)\b(bug|error|fix|issue|problem|exception|fails|crash)\b'

- labels: ["critical"]
  title: '(?i)\b(critical|urgent)\b'
  body: '(?i)\b(critical|urgent)\b'

- labels: ["enhancement"]
  title: '(?i)\b(feature|feat|enhancement|suggestion|addition|implement|improve)\b'
  body: '(?i)\b(feature|feat|enhancement|suggestion|addition|implement|improve)\b'

- labels: ["documentation"]
  title: '(?i)\b(documentation|docs|readme|guide|tutorial|instructions)\b'
  body: '(?i)\b(documentation|docs|readme|guide|tutorial|instructions)\b'

- labels: ["question"]
  title: '(?i)\b(question|how to|help|doubt|ask)\b'
  body: '(?i)\b(question|how to|help|doubt|ask)\b'

- labels: ["ui"]
  title: '(?i)\b(ui|design|style|css|layout)\b'
  body: '(?i)\b(ui|design|style|css|layout)\b'

- labels: ["backend"]
  title: '(?i)\b(backend|server|api|database|db|prisma|fastify|auth|jwt)\b'
  body: '(?i)\b(backend|server|api|database|db|prisma|fastify|auth|jwt)\b'

- labels: ["frontend"]
  title: '(?i)\b(frontend|client|react|tailwind|vite|page|component|hook|axios)\b'
  body: '(?i)\b(frontend|client|react|tailwind|vite|page|component|hook|axios)\b'

- labels: ["testing"]
  title: '(?i)\b(test|tests|testing|vitest|jest|testing-library|user-event|e2e|unit test)\b'
  body: '(?i)\b(test|tests|testing|vitest|jest|testing-library|user-event|e2e|unit test)\b'

- labels: ["refactor"]
  title: '(?i)\b(refactor|cleanup|chore|technical debt|optimization)\b'
  body: '(?i)\b(refactor|cleanup|chore|technical debt|optimization)\b'

- labels: ["ci/cd"]
  title: '(?i)\b(ci|cd|github actions|workflow|workflows|deployment|build)\b'
  body: '(?i)\b(ci|cd|github actions|workflow|workflows|deployment|build)\b'

- labels: ["config"]
  title: '(?i)\b(config|configuration|setup|env|tsconfig|vite\.config|tailwind\.config)\b'
  body: '(?i)\b(config|configuration|setup|env|tsconfig|vite\.config|tailwind\.config)\b'

- labels: ["needs-info"]
  title: '(?i)\b(incomplete|missing info|more details)\b'
  body: '(?i)\b(incomplete|missing info|more details)\b'

- labels: ["dependencies"]
  title: '(?i)\b(dependencies|deps|package|npm|dependabot|vulnerability)\b'
  body: '(?i)\b(dependencies|deps|package|npm|dependabot|vulnerability)\b'

- labels: ["good first issue"]
  title: '(?i)\b(good first issue)\b'
  body: '(?i)\b(good first issue)\b'

- labels: ["help wanted"]
  title: '(?i)\b(help wanted)\b'
  body: '(?i)\b(help wanted)\b'